version: '3'

services:
  postgres_db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - 5431:5432
    container_name: postgres_db
    volumes:
      - db:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio_storage:/data
    env_file: .env
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    container_name: database_gui
    depends_on:
      - postgres_db

volumes:
  db:
